# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kultainen Tomaatti
email: gt@as.fi
description: > # this means to ignore newlines until "baseurl:"
  Kultainen Tomaatti (GT) on Aalto-yliopiston Automaatio- ja systeemitekniikan killan kiltalehti.
url: "http://gt.as.fi" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude project files from build
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

lang: fi

# Remember to update when releasing a new magazine
# Use format D/YYYY (for example 1/2017)
latest_magazine: 1/2017
latest_magazine_description: Vuoden 2017 ensimm√§inen Kultainen Tomaatti julkaistiin 23.2 Automaatio- ja systeemitekniikan killan kiltakokouksessa.